# Generated by Django 5.2.4 on 2026-03-05 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_mood_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text="User's rating (1-5 stars)")),
                ('review', models.TextField(blank=True, help_text='Optional review text')),
                ('helpful_count', models.PositiveIntegerField(default=0, help_text='Number of users who found this helpful')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='accounts.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='accounts_us_user_id_9742de_idx'), models.Index(fields=['book', 'rating'], name='accounts_us_book_id_4e06aa_idx')],
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.CreateModel(
            name='UserGenrePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.DecimalField(decimal_places=2, default=0.5, help_text="Preference weight based on user's ratings and interactions", max_digits=3)),
                ('interaction_count', models.PositiveIntegerField(default=0)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.genre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-weight'],
                'indexes': [models.Index(fields=['user', 'weight'], name='accounts_us_user_id_657c47_idx')],
                'unique_together': {('user', 'genre')},
            },
        ),
        migrations.CreateModel(
            name='UserMoodHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mood_scores', models.JSONField(default=dict, help_text="User's reported mood distribution")),
                ('dominant_mood', models.CharField(help_text='Primary mood at the time of recording', max_length=30)),
                ('context', models.TextField(blank=True, help_text='What the user was looking for (mood in natural language)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User mood history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='accounts_us_user_id_b59dd3_idx'), models.Index(fields=['user', 'dominant_mood'], name='accounts_us_user_id_382adc_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_moods', models.JSONField(blank=True, default=dict, help_text="User's preferred emotional tones (e.g., {'happy': 0.8, 'relaxed': 0.6})")),
                ('preferred_sentiment', models.DecimalField(blank=True, decimal_places=2, help_text="User's preference on sentiment spectrum (negative to positive)", max_digits=3, null=True)),
                ('preferred_intensity', models.DecimalField(blank=True, decimal_places=2, help_text="User's preference for emotional intensity in books", max_digits=3, null=True)),
                ('min_rating', models.DecimalField(decimal_places=2, default=3.0, help_text='Minimum book rating to consider', max_digits=3)),
                ('min_ratings_count', models.PositiveIntegerField(default=10, help_text='Minimum number of ratings a book should have')),
                ('favorite_genres', models.ManyToManyField(blank=True, help_text="User's favorite genres for filtering", related_name='favorite_by_users', to='accounts.genre')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='accounts_us_user_id_806298_idx')],
            },
        ),
    ]
