# Generated by Django 5.2.12 on 2026-03-06 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_user_preference_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='PDF file for the book', null=True, upload_to='books/pdfs/'),
        ),
        migrations.AddField(
            model_name='book',
            name='pdf_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='When the PDF was uploaded', null=True),
        ),
        migrations.CreateModel(
            name='UserBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_number', models.PositiveIntegerField(help_text='Page number of the bookmark')),
                ('label', models.CharField(blank=True, help_text='Custom label or note for the bookmark', max_length=255)),
                ('color', models.CharField(choices=[('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('red', 'Red'), ('purple', 'Purple')], default='yellow', help_text='Color for visual organization', max_length=20)),
                ('bookmark_type', models.CharField(choices=[('note', 'Note'), ('highlight', 'Highlight'), ('bookmark', 'Bookmark')], default='bookmark', help_text='Type of bookmark', max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookmarks', to='accounts.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User bookmarks',
                'ordering': ['page_number'],
                'indexes': [models.Index(fields=['user', 'book'], name='accounts_us_user_id_fb436d_idx'), models.Index(fields=['book', 'page_number'], name='accounts_us_book_id_caf627_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_page', models.PositiveIntegerField(default=0, help_text='Current page number the user is on')),
                ('total_pages', models.PositiveIntegerField(blank=True, help_text='Total number of pages in the PDF', null=True)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Reading progress as percentage (0-100)', max_digits=5)),
                ('last_read_at', models.DateTimeField(auto_now=True, help_text='When the user last read this book')),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='Total time spent reading this book in seconds')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='not_started', help_text='Current reading status', max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to='accounts.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User reading sessions',
                'ordering': ['-last_read_at'],
                'indexes': [models.Index(fields=['user', 'last_read_at'], name='accounts_us_user_id_cd95e7_idx'), models.Index(fields=['book', 'status'], name='accounts_us_book_id_54ea4e_idx')],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
